spring.application.name=perfulandiaSPA

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@bhvzt196000qwk2y_high?TNS_ADMIN=/Users/camus/OneDrive/Escritorio/Duoc/3er Semestre/Desarrollo Fullstack I/Unidad 2/Evaluacion Formativa/walletbdd/Wallet_BHVZT196000QWK2Y

spring.datasource.username=ADMIN
spring.datasource.password=FullStack-001
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

logging.level.org.hibernate=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.java.sql=DEBUG